spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/suleymancompany?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8099